networks:
  mapmanager:
    driver: bridge

services:
  phpfpm:
    container_name: phpfpm
    image: bitnami/php-fpm:7.4
    ports:
      - 9000:9000
    volumes:
      - ./webRoot:/app
      - ./containerConfigs/phpfpm/php.ini:/opt/bitnami/php/etc/php.ini
    networks:
      - mapmanager

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - mapmanager
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./containerConfigs/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/yourapp.conf
      - ./webRoot:/app

  mapserver:
    container_name: MapServer
    image: camptocamp/mapserver:7.6
    networks:
      - mapmanager
    ports:
      - "6778:80"

  db:
    container_name: Postgres
    image: postgres:latest
    networks:
      - mapmanager
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webDevDB
    volumes:
      - ./containerConfigs/pg:/var/lib/postgresql/data:z
    ports:
      - 5432:5432

  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4
    networks:
      - mapmanager
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - ./containerConfigs/pgadmin:/var/lib/pgadmin
      - ./containerConfigs/pgadmin:/pgadmin4/servers.json
      - ./containerConfigs/pgadmin:/certs/server.cert
      - ./containerConfigs/pgadmin:/certs/server.key
    ports:
      - "5050:5050"
    depends_on:
      - db

  openldap:
    image: osixia/openldap:1.5.0
    networks:
      - mapmanager
    container_name: LDAP
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "webdevlocal"
      LDAP_DOMAIN: "webdevlocal.com"
      LDAP_BASE_DN: "dc=webdevlocal,dc=com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ./containerConfigs/openLDAP:/var/lib/ldap
      - ./containerConfigs/openLDAP:/etc/ldap/slapd.d
      - ./containerConfigs/openLDAP:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "example.org"
    hostname: "ldap-server"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: LDAPAdminPanel
    networks:
      - mapmanager
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "6060:80"
    depends_on:
      - openldap
      - mapserver

    
    