networks:
  mapmanager:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  ldap:

services:
  phpfpm:
    container_name: phpfpm
    image: bitnami/php-fpm:7.4
    ports:
      - 9000:9000
    volumes:
      - ./webRoot:/app
      - ./mapfiles:/mapfiles
      - ./containerConfigs/phpfpm/php.ini:/opt/bitnami/php/etc/php.ini
    networks:
      - mapmanager

  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - mapmanager
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./containerConfigs/nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/yourapp.conf
      - ./webRoot:/app

  mapserver:
    container_name: MapServer
    image: camptocamp/mapserver
    networks:
      - mapmanager
    ports:
      - "6778:80"
    volumes:
      - ./webRoot:/etc/mapserver/
  postgres:
    container_name: Postgres
    image: postgres:latest
    networks:
      - mapmanager
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webDevDB
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4
    networks:
      - mapmanager
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/var/lib/pgadmin
      - pgadmin:/pgadmin4/servers.json
      - pgadmin:/certs/server.cert
      - pgadmin:/certs/server.key
    ports:
      - "5055:5050"
    depends_on:
      - postgres
    