-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."group"
(
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying NOT NULL,
    PRIMARY KEY (uuid)
    );

CREATE TABLE IF NOT EXISTS public.map
(
    name character varying NOT NULL,
    uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    description character varying NOT NULL,
    "creationDate" date NOT NULL,
    "groupUUID" uuid NOT NULL,
    PRIMARY KEY (uuid)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    "LDAP-UUID" uuid NOT NULL DEFAULT gen_random_uuid(),
    PRIMARY KEY ("LDAP-UUID")
    );

CREATE TABLE IF NOT EXISTS public.rel_user_group
(
    "user_LDAP-UUID" uuid NOT NULL,
    group_uuid uuid NOT NULL
);

ALTER TABLE IF EXISTS public.map
    ADD CONSTRAINT "groupUUID" FOREIGN KEY ("groupUUID")
    REFERENCES public."group" (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_user_group
    ADD FOREIGN KEY ("user_LDAP-UUID")
    REFERENCES public."user" ("LDAP-UUID") MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_user_group
    ADD FOREIGN KEY (group_uuid)
    REFERENCES public."group" (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;