-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."group"
(
    uuid uuid NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (uuid)
    );

CREATE TABLE IF NOT EXISTS public.map
(
    name character varying NOT NULL,
    uuid uuid NOT NULL,
    description character varying NOT NULL,
    "creationDate" date NOT NULL,
    "groupUUID" uuid NOT NULL,
    PRIMARY KEY (uuid)
    );

CREATE TABLE IF NOT EXISTS public."user"
(
    ad_id character varying NOT NULL,
    PRIMARY KEY (ad_id)
    );

CREATE TABLE IF NOT EXISTS public.rel_user_group
(
    user_ad_id character varying NOT NULL,
    group_uuid uuid NOT NULL
);

ALTER TABLE IF EXISTS public.map
    ADD CONSTRAINT "groupUUID" FOREIGN KEY ("groupUUID")
    REFERENCES public."group" (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_user_group
    ADD FOREIGN KEY (user_ad_id)
    REFERENCES public."user" (ad_id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rel_user_group
    ADD FOREIGN KEY (group_uuid)
    REFERENCES public."group" (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;